<a href="https://colab.research.google.com/github/ag22042008/data-Science-notebooks/blob/main/annimplementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import tensorflow as tf  #tenserflow is engine keras is driving wheel keras uses tenserflow
from tensorflow import keras
from sklearn.model_selection import train_test_split
from  tensorflow.keras import layers
import pandas as pd

In [21]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [22]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [23]:
X=df.drop('needs_water',axis=1)
y=df['needs_water']

In [24]:
X

    soil_moisture  temperature_c  sunlight_hours
0            0.10             34               9
1            0.15             30               8
2            0.20             26               7
3            0.25             22               4
4            0.40             28               8
5            0.60             30              10
6            0.35             19               3
7            0.18             22              10
8            0.45             35              12
9            0.05             24               5
10           0.80             33               9
11           0.27             33              11
12           0.55             21               2
13           0.70             25               6
14           0.12             20               1
15           0.30             29               9

In [25]:
X_min=X.min()
x_max=X.max()
X_std=(X-X_min)/(x_max-X_min+1e-8)

In [26]:
X_std

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X_std, y, test_size=0.45, random_state=42,stratify=y)

In [28]:
model=keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [29]:
model.compile(loss='binary_crossentropy',optimizer='sgd',metrics=['accuracy'])

In [30]:
history=model.fit(X_train.values,y_train.values,
                  validation_data=(X_test,y_test),
                  epochs=100,batch_size=4,verbose=1)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 193ms/step - accuracy: 0.8750 - loss: 0.6667 - val_accuracy: 0.8750 - val_loss: 0.6780
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8750 - loss: 0.6657 - val_accuracy: 0.8750 - val_loss: 0.6777
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step - accuracy: 0.8750 - loss: 0.6651 - val_accuracy: 0.8750 - val_loss: 0.6774
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8750 - loss: 0.6646 - val_accuracy: 0.8750 - val_loss: 0.6771
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.8750 - loss: 0.6644 - val_accuracy: 0.8750 - val_loss: 0.6768
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.8750 - loss: 0.6635 - val_accuracy: 0.8750 - val_loss: 0.6766
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.8750 - loss: 0.6633 - val_accuracy: 0.8750 - val_loss: 0.6764
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.6629 - val_accuracy: 0.8750 - val_loss: 0.6762
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8750 - loss: 0.6625 - val_accuracy: 0.8750 - val_loss: 0.6760
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.6620 - val_accuracy: 0.8750 - val_loss: 0.6758
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.6615 - val_accuracy: 0.8750 - val_loss: 0.6756
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.6612 - val_accuracy: 0.8750 - val_loss: 0.6754
Epoch 13/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.6603 - val_accuracy: 0.8750 - val_loss: 0.6752
Epoch 14/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 1.0000 - loss: 0.6598 - val_accuracy: 0.8750 - val_loss: 0.6750
Epoch 15/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.6599 - val_accuracy: 0.8750 - val_loss: 0.6747
Epoch 16/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 1.0000 - loss: 0.6590 - val_accuracy: 0.7500 - val_loss: 0.6745
Epoch 17/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.6590 - val_accuracy: 0.7500 - val_loss: 0.6743
Epoch 18/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.6582 - val_accuracy: 0.7500 - val_loss: 0.6741
Epoch 19/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.6582 - val_accuracy: 0.7500 - val_loss: 0.6738
Epoch 20/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.6574 - val_accuracy: 0.7500 - val_loss: 0.6736
Epoch 21/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.6575 - val_accuracy: 0.7500 - val_loss: 0.6734
Epoch 22/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.6565 - val_accuracy: 0.7500 - val_loss: 0.6732
Epoch 23/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.6566 - val_accuracy: 0.7500 - val_loss: 0.6730
Epoch 24/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 1.0000 - loss: 0.6561 - val_accuracy: 0.7500 - val_loss: 0.6727
Epoch 25/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.6557 - val_accuracy: 0.7500 - val_loss: 0.6725
Epoch 26/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.6549 - val_accuracy: 0.7500 - val_loss: 0.6723
Epoch 27/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 1.0000 - loss: 0.6545 - val_accuracy: 0.7500 - val_loss: 0.6721
Epoch 28/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 1.0000 - loss: 0.6540 - val_accuracy: 0.7500 - val_loss: 0.6719
Epoch 29/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.6556 - val_accuracy: 0.7500 - val_loss: 0.6716
Epoch 30/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.6532 - val_accuracy: 0.7500 - val_loss: 0.6714
Epoch 31/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.6529 - val_accuracy: 0.7500 - val_loss: 0.6712
Epoch 32/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.6529 - val_accuracy: 0.7500 - val_loss: 0.6711
Epoch 33/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.6528 - val_accuracy: 0.7500 - val_loss: 0.6709
Epoch 34/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.6519 - val_accuracy: 0.7500 - val_loss: 0.6707
Epoch 35/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8750 - loss: 0.6516 - val_accuracy: 0.7500 - val_loss: 0.6705
Epoch 36/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.8750 - loss: 0.6513 - val_accuracy: 0.7500 - val_loss: 0.6703
Epoch 37/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.8750 - loss: 0.6510 - val_accuracy: 0.7500 - val_loss: 0.6702
Epoch 38/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8750 - loss: 0.6506 - val_accuracy: 0.7500 - val_loss: 0.6700
Epoch 39/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.8750 - loss: 0.6507 - val_accuracy: 0.7500 - val_loss: 0.6698
Epoch 40/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.8750 - loss: 0.6500 - val_accuracy: 0.7500 - val_loss: 0.6696
Epoch 41/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.8750 - loss: 0.6497 - val_accuracy: 0.7500 - val_loss: 0.6694
Epoch 42/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.8750 - loss: 0.6498 - val_accuracy: 0.7500 - val_loss: 0.6693
Epoch 43/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.8750 - loss: 0.6491 - val_accuracy: 0.7500 - val_loss: 0.6691
Epoch 44/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8750 - loss: 0.6492 - val_accuracy: 0.7500 - val_loss: 0.6689
Epoch 45/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.8750 - loss: 0.6492 - val_accuracy: 0.7500 - val_loss: 0.6687
Epoch 46/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.8750 - loss: 0.6487 - val_accuracy: 0.7500 - val_loss: 0.6685
Epoch 47/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.8750 - loss: 0.6478 - val_accuracy: 0.7500 - val_loss: 0.6684
Epoch 48/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.8750 - loss: 0.6480 - val_accuracy: 0.8750 - val_loss: 0.6682
Epoch 49/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.8750 - loss: 0.6472 - val_accuracy: 0.8750 - val_loss: 0.6680
Epoch 50/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.8750 - loss: 0.6473 - val_accuracy: 0.8750 - val_loss: 0.6678
Epoch 51/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.8750 - loss: 0.6470 - val_accuracy: 0.8750 - val_loss: 0.6676
Epoch 52/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.7500 - loss: 0.6466 - val_accuracy: 0.8750 - val_loss: 0.6675
Epoch 53/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8750 - loss: 0.6464 - val_accuracy: 0.8750 - val_loss: 0.6673
Epoch 54/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8750 - loss: 0.6461 - val_accuracy: 0.8750 - val_loss: 0.6671
Epoch 55/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.8750 - loss: 0.6459 - val_accuracy: 0.8750 - val_loss: 0.6669
Epoch 56/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8750 - loss: 0.6449 - val_accuracy: 0.8750 - val_loss: 0.6668
Epoch 57/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8750 - loss: 0.6447 - val_accuracy: 0.8750 - val_loss: 0.6666
Epoch 58/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8750 - loss: 0.6448 - val_accuracy: 0.8750 - val_loss: 0.6664
Epoch 59/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8750 - loss: 0.6445 - val_accuracy: 0.8750 - val_loss: 0.6662
Epoch 60/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.8750 - loss: 0.6437 - val_accuracy: 0.8750 - val_loss: 0.6660
Epoch 61/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.8750 - loss: 0.6455 - val_accuracy: 0.8750 - val_loss: 0.6659
Epoch 62/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8750 - loss: 0.6430 - val_accuracy: 0.8750 - val_loss: 0.6657
Epoch 63/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8750 - loss: 0.6427 - val_accuracy: 0.8750 - val_loss: 0.6655
Epoch 64/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - loss: 0.6428 - val_accuracy: 0.8750 - val_loss: 0.6653
Epoch 65/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.8750 - loss: 0.6422 - val_accuracy: 0.8750 - val_loss: 0.6652
Epoch 66/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8750 - loss: 0.6418 - val_accuracy: 0.8750 - val_loss: 0.6650
Epoch 67/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8750 - loss: 0.6415 - val_accuracy: 0.8750 - val_loss: 0.6648
Epoch 68/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8750 - loss: 0.6412 - val_accuracy: 0.8750 - val_loss: 0.6646
Epoch 69/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8750 - loss: 0.6409 - val_accuracy: 0.8750 - val_loss: 0.6645
Epoch 70/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8750 - loss: 0.6405 - val_accuracy: 0.8750 - val_loss: 0.6643
Epoch 71/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7500 - loss: 0.6407 - val_accuracy: 0.8750 - val_loss: 0.6641
Epoch 72/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - loss: 0.6405 - val_accuracy: 0.8750 - val_loss: 0.6639
Epoch 73/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7500 - loss: 0.6400 - val_accuracy: 0.8750 - val_loss: 0.6637
Epoch 74/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7500 - loss: 0.6392 - val_accuracy: 0.8750 - val_loss: 0.6636
Epoch 75/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7500 - loss: 0.6396 - val_accuracy: 0.7500 - val_loss: 0.6634
Epoch 76/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7500 - loss: 0.6391 - val_accuracy: 0.7500 - val_loss: 0.6632
Epoch 77/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - loss: 0.6388 - val_accuracy: 0.7500 - val_loss: 0.6630
Epoch 78/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7500 - loss: 0.6380 - val_accuracy: 0.7500 - val_loss: 0.6629
Epoch 79/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - loss: 0.6377 - val_accuracy: 0.7500 - val_loss: 0.6627
Epoch 80/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - loss: 0.6373 - val_accuracy: 0.7500 - val_loss: 0.6625
Epoch 81/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7500 - loss: 0.6370 - val_accuracy: 0.7500 - val_loss: 0.6623
Epoch 82/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.7500 - loss: 0.6372 - val_accuracy: 0.7500 - val_loss: 0.6622
Epoch 83/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.7500 - loss: 0.6363 - val_accuracy: 0.7500 - val_loss: 0.6620
Epoch 84/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7500 - loss: 0.6365 - val_accuracy: 0.7500 - val_loss: 0.6618
Epoch 85/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 220ms/step - accuracy: 0.7500 - loss: 0.6379 - val_accuracy: 0.7500 - val_loss: 0.6616
Epoch 86/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.7500 - loss: 0.6354 - val_accuracy: 0.7500 - val_loss: 0.6614
Epoch 87/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7500 - loss: 0.6355 - val_accuracy: 0.7500 - val_loss: 0.6613
Epoch 88/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - loss: 0.6351 - val_accuracy: 0.7500 - val_loss: 0.6611
Epoch 89/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7500 - loss: 0.6344 - val_accuracy: 0.7500 - val_loss: 0.6609
Epoch 90/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.7500 - loss: 0.6341 - val_accuracy: 0.7500 - val_loss: 0.6607
Epoch 91/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7500 - loss: 0.6343 - val_accuracy: 0.7500 - val_loss: 0.6606
Epoch 92/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - accuracy: 0.7500 - loss: 0.6334 - val_accuracy: 0.7500 - val_loss: 0.6604
Epoch 93/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - loss: 0.6331 - val_accuracy: 0.7500 - val_loss: 0.6602
Epoch 94/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7500 - loss: 0.6350 - val_accuracy: 0.7500 - val_loss: 0.6600
Epoch 95/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7500 - loss: 0.6325 - val_accuracy: 0.7500 - val_loss: 0.6598
Epoch 96/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7500 - loss: 0.6321 - val_accuracy: 0.7500 - val_loss: 0.6597
Epoch 97/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7500 - loss: 0.6326 - val_accuracy: 0.7500 - val_loss: 0.6595
Epoch 98/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7500 - loss: 0.6319 - val_accuracy: 0.7500 - val_loss: 0.6593
Epoch 99/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7500 - loss: 0.6312 - val_accuracy: 0.7500 - val_loss: 0.6591
Epoch 100/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7500 - loss: 0.6313 - val_accuracy: 0.7500 - val_loss: 0.6590